package tests;

import org.testng.annotations.Test;

public class ChatText extends BaseTest {

    @Test
    public void sendMessage() {
        String text = "Autotest";
        chatPage.openPage()
                .writeText(text)
                .clickSend()
                .messageShouldExist(1, text);
    }

    @Test
    public void sendMessageByEnter() {
        String text = "Autotest";
        chatPage
                .openPage()
//                .writeText(text)
                .clickEnter()
                .messageShouldExist(1, text);
    }

    @Test
    public void sendLongMessage() {
        String longMessage = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque luctus nulla nec turpis consectetur, id tincidunt nibh molestie. Nam dapibus ornare nulla ut tempus. Aliquam luctus nunc risus. Quisque gravida mattis nibh non maximus. Quisque ac ultricies metus, vitae fringilla leo. Phasellus augue nunc, ultricies eget velit in, eleifend scelerisque nisi. Cras pellentesque nisl ut volutpat placerat. Aliquam convallis ultricies nulla, vel semper augue bibendum nec. Vivamus viverra felis volutpat eros faucibus sagittis. Sed id magna congue, tempus turpis sed, volutpat quam." +
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque luctus nulla nec turpis consectetur, id tincidunt nibh molestie. Nam dapibus ornare nulla ut tempus. Aliquam luctus nunc risus. Quisque gravida mattis nibh non maximus. Quisque ac ultricies metus, vitae fringilla leo. Phasellus augue nunc, ultricies eget velit in, eleifend scelerisque nisi. Cras pellentesque nisl ut volutpat placerat. Aliquam convallis ultricies nulla, vel semper augue bibendum nec. Vivamus viverra felis volutpat eros faucibus sagittis. Sed id magna congue, tempus turpis sed, volutpat quam." +
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque luctus nulla nec turpis consectetur, id tincidunt nibh molestie. Nam dapibus ornare nulla ut tempus. Aliquam luctus nunc risus. Quisque gravida mattis nibh non maximus. Quisque ac ultricies metus, vitae fringilla leo. Phasellus augue nunc, ultricies eget velit in, eleifend scelerisque nisi. Cras pellentesque nisl ut volutpat placerat. Aliquam convallis ultricies nulla, vel semper augue bibendum nec. Vivamus viverra felis volutpat eros faucibus sagittis. Sed id magna congue, tempus turpis sed, volutpat quam." +
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque luctus nulla nec turpis consectetur, id tincidunt nibh molestie. Nam dapibus ornare nulla ut tempus. Aliquam luctus nunc risus. Quisque gravida mattis nibh non maximus. Quisque ac ultricies metus, vitae fringilla leo. Phasellus augue nunc, ultricies eget velit in, eleifend scelerisque nisi. Cras pellentesque nisl ut volutpat placerat. Aliquam convallis ultricies nulla, vel semper augue bibendum nec. Vivamus viverra felis volutpat eros faucibus sagittis. Sed id magna congue, tempus turpis sed, volutpat quam." +
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque luctus nulla nec turpis consectetur, id tincidunt nibh molestie. Nam dapibus ornare nulla ut tempus. Aliquam luctus nunc risus. Quisque gravida mattis nibh non maximus. Quisque ac ultricies metus, vitae fringilla leo. Phasellus augue nunc, ultricies eget velit in, eleifend scelerisque nisi. Cras pellentesque nisl ut volutpat placerat. Aliquam convallis ultricies nulla, vel semper augue bibendum nec. Vivamus viverra felis volutpat eros faucibus sagittis. Sed id magna congue, tempus turpis sed, volutpat quam." +
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque luctus nulla nec turpis consectetur, id tincidunt nibh molestie. Nam dapibus ornare nulla ut tempus. Aliquam luctus nunc risus. Quisque gravida mattis nibh non maximus. Quisque ac ultricies metus, vitae fringilla leo. Phasellus augue nunc, ultricies eget velit in, eleifend scelerisque nisi. Cras pellentesque nisl ut volutpat placerat. Aliquam convallis ultricies nulla, vel semper augue bibendum nec. Vivamus viverra felis volutpat eros faucibus sagittis. Sed id magna congue, tempus turpis sed, volutpat quam." +
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque luctus nulla nec turpis consectetur, id tincidunt nibh molestie. Nam dapibus ornare nulla ut tempus. Aliquam luctus nunc risus. Quisque gravida mattis nibh non maximus. Quisque ac ultricies metus, vitae fringilla leo. Phasellus augue nunc, ultricies eget velit in, eleifend scelerisque nisi. Cras pellentesque nisl ut volutpat placerat. Aliquam convallis ultricies nulla, vel semper augue bibendum nec. Vivamus viverra felis volutpat eros faucibus sagittis. Sed id magna congue, tempus turpis sed, volutpat quam." +
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque luctus nulla nec turpis consectetur, id tincidunt nibh molestie. Nam dapibus ornare nulla ut tempus. Aliquam luctus nunc risus. Quisque gravida mattis nibh non maximus. Quisque ac ultricies metus, vitae fringilla leo. Phasellus augue nunc, ultricies eget velit in, eleifend scelerisque nisi. Cras pellentesque nisl ut volutpat placerat. Aliquam convallis ultricies nulla, vel semper augue bibendum nec. Vivamus viverra felis volutpat eros faucibus sagittis. Sed id magna congue, tempus turpis sed, volutpat quam." +
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque luctus nulla nec turpis consectetur, id tincidunt nibh molestie. Nam dapibus ornare nulla ut tempus. Aliquam luctus nunc risus. Quisque gravida mattis nibh non maximus. Quisque ac ultricies metus, vitae fringilla leo. Phasellus augue nunc, ultricies eget velit in, eleifend scelerisque nisi. Cras pellentesque nisl ut volutpat placerat. Aliquam convallis ultricies nulla, vel semper augue bibendum nec. Vivamus viverra felis volutpat eros faucibus sagittis. Sed id magna congue, tempus turpis sed, volutpat quam." +
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque luctus nulla nec turpis consectetur, id tincidunt nibh molestie. Nam dapibus ornare nulla ut tempus. Aliquam luctus nunc risus. Quisque gravida mattis nibh non maximus. Quisque ac ultricies metus, vitae fringilla leo. Phasellus augue nunc, ultricies eget velit in, eleifend scelerisque nisi. Cras pellentesque nisl ut volutpat placerat. Aliquam convallis ultricies nulla, vel semper augue bibendum nec. Vivamus viverra felis volutpat eros faucibus sagittis. Sed id magna congue, tempus turpis sed, volutpat quam." +
                "Sed vulputate, lacus nec egestas lacinia, enim neque fringilla ipsum, nec molestie nulla nisi malesuada libero. Ut nulla arcu, dapibus imperdiet vehicula quis, malesuada sit amet ipsum. Ut maximus odio a velit dignissim, a auctor turpis ullamcorper. Praesent metus neque, maximus vel pulvinar tincidunt, consectetur quis leo. In ipsum sem, rutrum sit amet sem ut, efficitur condimentum lorem. Nullam malesuada tortor id eros cursus, a tempus nisi feugiat. Etiam eleifend mauris sed tellus ullamcorper ornare. Vestibulum lacinia imperdiet lacus eget fermentum. Duis iaculis urna turpis, vel ornare elit tincidunt at. Morbi hendrerit gravida diam id suscipit." +
                "Sed vulputate, lacus nec egestas lacinia, enim neque fringilla ipsum, nec molestie nulla nisi malesuada libero. Ut nulla arcu, dapibus imperdiet vehicula quis, malesuada sit amet ipsum. Ut maximus odio a velit dignissim, a auctor turpis ullamcorper. Praesent metus neque, maximus vel pulvinar tincidunt, consectetur quis leo. In ipsum sem, rutrum sit amet sem ut, efficitur condimentum lorem. Nullam malesuada tortor id eros cursus, a tempus nisi feugiat. Etiam eleifend mauris sed tellus ullamcorper ornare. Vestibulum lacinia imperdiet lacus eget fermentum. Duis iaculis urna turpis, vel ornare elit tincidunt at. Morbi hendrerit gravida diam id suscipit." +
                "Sed vulputate, lacus nec egestas lacinia, enim neque fringilla ipsum, nec molestie nulla nisi malesuada libero. Ut nulla arcu, dapibus imperdiet vehicula quis, malesuada sit amet ipsum. Ut maximus odio a velit dignissim, a auctor turpis ullamcorper. Praesent metus neque, maximus vel pulvinar tincidunt, consectetur quis leo. In ipsum sem, rutrum sit amet sem ut, efficitur condimentum lorem. Nullam malesuada tortor id eros cursus, a tempus nisi feugiat. Etiam eleifend mauris sed tellus ullamcorper ornare. Vestibulum lacinia imperdiet lacus eget fermentum. Duis iaculis urna turpis, vel ornare elit tincidunt at. Morbi hendrerit gravida diam id suscipit." +
                "Sed vulputate, lacus nec egestas lacinia, enim neque fringilla ipsum, nec molestie nulla nisi malesuada libero. Ut nulla arcu, dapibus imperdiet vehicula quis, malesuada sit amet ipsum. Ut maximus odio a velit dignissim, a auctor turpis ullamcorper. Praesent metus neque, maximus vel pulvinar tincidunt, consectetur quis leo. In ipsum sem, rutrum sit amet sem ut, efficitur condimentum lorem. Nullam malesuada tortor id eros cursus, a tempus nisi feugiat. Etiam eleifend mauris sed tellus ullamcorper ornare. Vestibulum lacinia imperdiet lacus eget fermentum. Duis iaculis urna turpis, vel ornare elit tincidunt at. Morbi hendrerit gravida diam id suscipit." +
                "Sed vulputate, lacus nec egestas lacinia, enim neque fringilla ipsum, nec molestie nulla nisi malesuada libero. Ut nulla arcu, dapibus imperdiet vehicula quis, malesuada sit amet ipsum. Ut maximus odio a velit dignissim, a auctor turpis ullamcorper. Praesent metus neque, maximus vel pulvinar tincidunt, consectetur quis leo. In ipsum sem, rutrum sit amet sem ut, efficitur condimentum lorem. Nullam malesuada tortor id eros cursus, a tempus nisi feugiat. Etiam eleifend mauris sed tellus ullamcorper ornare. Vestibulum lacinia imperdiet lacus eget fermentum. Duis iaculis urna turpis, vel ornare elit tincidunt at. Morbi hendrerit gravida diam id suscipit." +
                "Sed vulputate, lacus nec egestas lacinia, enim neque fringilla ipsum, nec molestie nulla nisi malesuada libero. Ut nulla arcu, dapibus imperdiet vehicula quis, malesuada sit amet ipsum. Ut maximus odio a velit dignissim, a auctor turpis ullamcorper. Praesent metus neque, maximus vel pulvinar tincidunt, consectetur quis leo. In ipsum sem, rutrum sit amet sem ut, efficitur condimentum lorem. Nullam malesuada tortor id eros cursus, a tempus nisi feugiat. Etiam eleifend mauris sed tellus ullamcorper ornare. Vestibulum lacinia imperdiet lacus eget fermentum. Duis iaculis urna turpis, vel ornare elit tincidunt at. Morbi hendrerit gravida diam id suscipit." +
                "Sed vulputate, lacus nec egestas lacinia, enim neque fringilla ipsum, nec molestie nulla nisi malesuada libero. Ut nulla arcu, dapibus imperdiet vehicula quis, malesuada sit amet ipsum. Ut maximus odio a velit dignissim, a auctor turpis ullamcorper. Praesent metus neque, maximus vel pulvinar tincidunt, consectetur quis leo. In ipsum sem, rutrum sit amet sem ut, efficitur condimentum lorem. Nullam malesuada tortor id eros cursus, a tempus nisi feugiat. Etiam eleifend mauris sed tellus ullamcorper ornare. Vestibulum lacinia imperdiet lacus eget fermentum. Duis iaculis urna turpis, vel ornare elit tincidunt at. Morbi hendrerit gravida diam id suscipit." +
                "Sed vulputate, lacus nec egestas lacinia, enim neque fringilla ipsum, nec molestie nulla nisi malesuada libero. Ut nulla arcu, dapibus imperdiet vehicula quis, malesuada sit amet ipsum. Ut maximus odio a velit dignissim, a auctor turpis ullamcorper. Praesent metus neque, maximus vel pulvinar tincidunt, consectetur quis leo. In ipsum sem, rutrum sit amet sem ut, efficitur condimentum lorem. Nullam malesuada tortor id eros cursus, a tempus nisi feugiat. Etiam eleifend mauris sed tellus ullamcorper ornare. Vestibulum lacinia imperdiet lacus eget fermentum. Duis iaculis urna turpis, vel ornare elit tincidunt at. Morbi hendrerit gravida diam id suscipit." +
                "Sed vulputate, lacus nec egestas lacinia, enim neque fringilla ipsum, nec molestie nulla nisi malesuada libero. Ut nulla arcu, dapibus imperdiet vehicula quis, malesuada sit amet ipsum. Ut maximus odio a velit dignissim, a auctor turpis ullamcorper. Praesent metus neque, maximus vel pulvinar tincidunt, consectetur quis leo. In ipsum sem, rutrum sit amet sem ut, efficitur condimentum lorem. Nullam malesuada tortor id eros cursus, a tempus nisi feugiat. Etiam eleifend mauris sed tellus ullamcorper ornare. Vestibulum lacinia imperdiet lacus eget fermentum. Duis iaculis urna turpis, vel ornare elit tincidunt at. Morbi hendrerit gravida diam id suscipit." +
                "Sed vulputate, lacus nec egestas lacinia, enim neque fringilla ipsum, nec molestie nulla nisi malesuada libero. Ut nulla arcu, dapibus imperdiet vehicula quis, malesuada sit amet ipsum. Ut maximus odio a velit dignissim, a auctor turpis ullamcorper. Praesent metus neque, maximus vel pulvinar tincidunt, consectetur quis leo. In ipsum sem, rutrum sit amet sem ut, efficitur condimentum lorem. Nullam malesuada tortor id eros cursus, a tempus nisi feugiat. Etiam eleifend mauris sed tellus ullamcorper ornare. Vestibulum lacinia imperdiet lacus eget fermentum. Duis iaculis urna turpis, vel ornare elit tincidunt at. Morbi hendrerit gravida diam id suscipit." +
                "Sed vulputate, lacus nec egestas lacinia, enim neque fringilla ipsum, nec molestie nulla nisi malesuada libero. Ut nulla arcu, dapibus imperdiet vehicula quis, malesuada sit amet ipsum. Ut maximus odio a velit dignissim, a auctor turpis ullamcorper. Praesent metus neque, maximus vel pulvinar tincidunt, consectetur quis leo. In ipsum sem, rutrum sit amet sem ut, efficitur condimentum lorem. Nullam malesuada tortor id eros cursus, a tempus nisi feugiat. Etiam eleifend mauris sed tellus ullamcorper ornare. Vestibulum lacinia imperdiet lacus eget fermentum. Duis iaculis urna turpis, vel ornare elit tincidunt at. Morbi hendrerit gravida diam id suscipit." +
                "Sed vulputate, lacus nec egestas lacinia, enim neque fringilla ipsum, nec molestie nulla nisi malesuada libero. Ut nulla arcu, dapibus imperdiet vehicula quis, malesuada sit amet ipsum. Ut maximus odio a velit dignissim, a auctor turpis ullamcorper. Praesent metus neque, maximus vel pulvinar tincidunt, consectetur quis leo. In ipsum sem, rutrum sit amet sem ut, efficitur condimentum lorem. Nullam malesuada tortor id eros cursus, a tempus nisi feugiat. Etiam eleifend mauris sed tellus ullamcorper ornare. Vestibulum lacinia imperdiet lacus eget fermentum. Duis iaculis urna turpis, vel ornare elit tincidunt at. Morbi hendrerit gravida diam id suscipit." +
                "Sed vulputate, lacus nec egestas lacinia, enim neque fringilla ipsum, nec molestie nulla nisi malesuada libero. Ut nulla arcu, dapibus imperdiet vehicula quis, malesuada sit amet ipsum. Ut maximus odio a velit dignissim, a auctor turpis ullamcorper. Praesent metus neque, maximus vel pulvinar tincidunt, consectetur quis leo. In ipsum sem, rutrum sit amet sem ut, efficitur condimentum lorem. Nullam malesuada tortor id eros cursus, a tempus nisi feugiat. Etiam eleifend mauris sed tellus ullamcorper ornare. Vestibulum lacinia imperdiet lacus eget fermentum. Duis iaculis urna turpis, vel ornare elit tincidunt at. Morbi hendrerit gravida diam id suscipit." +
                "Sed vulputate, lacus nec egestas lacinia, enim neque fringilla ipsum, nec molestie nulla nisi malesuada libero. Ut nulla arcu, dapibus imperdiet vehicula quis, malesuada sit amet ipsum. Ut maximus odio a velit dignissim, a auctor turpis ullamcorper. Praesent metus neque, maximus vel pulvinar tincidunt, consectetur quis leo. In ipsum sem, rutrum sit amet sem ut, efficitur condimentum lorem. Nullam malesuada tortor id eros cursus, a tempus nisi feugiat. Etiam eleifend mauris sed tellus ullamcorper ornare. Vestibulum lacinia imperdiet lacus eget fermentum. Duis iaculis urna turpis, vel ornare elit tincidunt at. Morbi hendrerit gravida diam id suscipit." +
                "Sed vulputate, lacus nec egestas lacinia, enim neque fringilla ipsum, nec molestie nulla nisi malesuada libero. Ut nulla arcu, dapibus imperdiet vehicula quis, malesuada sit amet ipsum. Ut maximus odio a velit dignissim, a auctor turpis ullamcorper. Praesent metus neque, maximus vel pulvinar tincidunt, consectetur quis leo. In ipsum sem, rutrum sit amet sem ut, efficitur condimentum lorem. Nullam malesuada tortor id eros cursus, a tempus nisi feugiat. Etiam eleifend mauris sed tellus ullamcorper ornare. Vestibulum lacinia imperdiet lacus eget fermentum. Duis iaculis urna turpis, vel ornare elit tincidunt at. Morbi hendrerit gravida diam id suscipit." +
                "Sed vulputate, lacus nec egestas lacinia, enim neque fringilla ipsum, nec molestie nulla nisi malesuada libero. Ut nulla arcu, dapibus imperdiet vehicula quis, malesuada sit amet ipsum. Ut maximus odio a velit dignissim, a auctor turpis ullamcorper. Praesent metus neque, maximus vel pulvinar tincidunt, consectetur quis leo. In ipsum sem, rutrum sit amet sem ut, efficitur condimentum lorem. Nullam malesuada tortor id eros cursus, a tempus nisi feugiat. Etiam eleifend mauris sed tellus ullamcorper ornare. Vestibulum lacinia imperdiet lacus eget fermentum. Duis iaculis urna turpis, vel ornare elit tincidunt at. Morbi hendrerit gravida diam id suscipit." +
                "Sed vulputate, lacus nec egestas lacinia, enim neque fringilla ipsum, nec molestie nulla nisi malesuada libero. Ut nulla arcu, dapibus imperdiet vehicula quis, malesuada sit amet ipsum. Ut maximus odio a velit dignissim, a auctor turpis ullamcorper. Praesent metus neque, maximus vel pulvinar tincidunt, consectetur quis leo. In ipsum sem, rutrum sit amet sem ut, efficitur condimentum lorem. Nullam malesuada tortor id eros cursus, a tempus nisi feugiat. Etiam eleifend mauris sed tellus ullamcorper ornare. Vestibulum lacinia imperdiet lacus eget fermentum. Duis iaculis urna turpis, vel ornare elit tincidunt at. Morbi hendrerit gravida diam id suscipit." +
                "Sed vulputate, lacus nec egestas lacinia, enim neque fringilla ipsum, nec molestie nulla nisi malesuada libero. Ut nulla arcu, dapibus imperdiet vehicula quis, malesuada sit amet ipsum. Ut maximus odio a velit dignissim, a auctor turpis ullamcorper. Praesent metus neque, maximus vel pulvinar tincidunt, consectetur quis leo. In ipsum sem, rutrum sit amet sem ut, efficitur condimentum lorem. Nullam malesuada tortor id eros cursus, a tempus nisi feugiat. Etiam eleifend mauris sed tellus ullamcorper ornare. Vestibulum lacinia imperdiet lacus eget fermentum. Duis iaculis urna turpis, vel ornare elit tincidunt at. Morbi hendrerit gravida diam id suscipit." +
                "Sed vulputate, lacus nec egestas lacinia, enim neque fringilla ipsum, nec molestie nulla nisi malesuada libero. Ut nulla arcu, dapibus imperdiet vehicula quis, malesuada sit amet ipsum. Ut maximus odio a velit dignissim, a auctor turpis ullamcorper. Praesent metus neque, maximus vel pulvinar tincidunt, consectetur quis leo. In ipsum sem, rutrum sit amet sem ut, efficitur condimentum lorem. Nullam malesuada tortor id eros cursus, a tempus nisi feugiat. Etiam eleifend mauris sed tellus ullamcorper ornare. Vestibulum lacinia imperdiet lacus eget fermentum. Duis iaculis urna turpis, vel ornare elit tincidunt at. Morbi hendrerit gravida diam id suscipit." +
                "Sed vulputate, lacus nec egestas lacinia, enim neque fringilla ipsum, nec molestie nulla nisi malesuada libero. Ut nulla arcu, dapibus imperdiet vehicula quis, malesuada sit amet ipsum. Ut maximus odio a velit dignissim, a auctor turpis ullamcorper. Praesent metus neque, maximus vel pulvinar tincidunt, consectetur quis leo. In ipsum sem, rutrum sit amet sem ut, efficitur condimentum lorem. Nullam malesuada tortor id eros cursus, a tempus nisi feugiat. Etiam eleifend mauris sed tellus ullamcorper ornare. Vestibulum lacinia imperdiet lacus eget fermentum. Duis iaculis urna turpis, vel ornare elit tincidunt at. Morbi hendrerit gravida diam id suscipit." +
                "Sed vulputate, lacus nec egestas lacinia, enim neque fringilla ipsum, nec molestie nulla nisi malesuada libero. Ut nulla arcu, dapibus imperdiet vehicula quis, malesuada sit amet ipsum. Ut maximus odio a velit dignissim, a auctor turpis ullamcorper. Praesent metus neque, maximus vel pulvinar tincidunt, consectetur quis leo. In ipsum sem, rutrum sit amet sem ut, efficitur condimentum lorem. Nullam malesuada tortor id eros cursus, a tempus nisi feugiat. Etiam eleifend mauris sed tellus ullamcorper ornare. Vestibulum lacinia imperdiet lacus eget fermentum. Duis iaculis urna turpis, vel ornare elit tincidunt at. Morbi hendrerit gravida diam id suscipit." +
                "Sed vulputate, lacus nec egestas lacinia, enim neque fringilla ipsum, nec molestie nulla nisi malesuada libero. Ut nulla arcu, dapibus imperdiet vehicula quis, malesuada sit amet ipsum. Ut maximus odio a velit dignissim, a auctor turpis ullamcorper. Praesent metus neque, maximus vel pulvinar tincidunt, consectetur quis leo. In ipsum sem, rutrum sit amet sem ut, efficitur condimentum lorem. Nullam malesuada tortor id eros cursus, a tempus nisi feugiat. Etiam eleifend mauris sed tellus ullamcorper ornare. Vestibulum lacinia imperdiet lacus eget fermentum. Duis iaculis urna turpis, vel ornare elit tincidunt at. Morbi hendrerit gravida diam id suscipit." +
                "Sed vulputate, lacus nec egestas lacinia, enim neque fringilla ipsum, nec molestie nulla nisi malesuada libero. Ut nulla arcu, dapibus imperdiet vehicula quis, malesuada sit amet ipsum. Ut maximus odio a velit dignissim, a auctor turpis ullamcorper. Praesent metus neque, maximus vel pulvinar tincidunt, consectetur quis leo. In ipsum sem, rutrum sit amet sem ut, efficitur condimentum lorem. Nullam malesuada tortor id eros cursus, a tempus nisi feugiat. Etiam eleifend mauris sed tellus ullamcorper ornare. Vestibulum lacinia imperdiet lacus eget fermentum. Duis iaculis urna turpis, vel ornare elit tincidunt at. Morbi hendrerit gravida diam id suscipit." +
                "";
        chatPage
                .openPage()
                .writeText(longMessage)
                .clickSend()
                .messageShouldExist(1, longMessage);
    }

    @Test
    public void sendEnterLink() {
        String link = "https://www.google.com/";
        chatPage
                .openPage()
                .writeText(link)
                .clickEnter()
                .linkText(1, link);
    }

    @Test
    public void messageContainingHTML() {
        String html = "<html><body><p>test</p></body></html>";
        chatPage
                .openPage()
                .writeText(html)
                .clickEnter()
                .messageShouldExist(1, html);
    }

    @Test
    public void editMessage() {
        chatPage
                .openPage()
                .writeText("Hello")
                .clickSend()
                .editMessage()
                .modifyTextMessage("Bye")
                .modifyText(1, "Bye");
    }

    @Test
    public void deleteMessage() {
        chatPage.openPage()
                .writeText("Hello")
                .clickSend()
                .deleteMessage()
                .deleteMessageText(1, "removed...");
    }

    @Test
    public void send11Messages() {
        String text = "Autotest";
        chatPage
                .openPage()
                .checkLimit(text);
    }
}
